model:
  arch: mini_gpt4_llama_v2
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 256
  low_resource: False
  image_size: 224
  end_sym: "</s>"
  llama_model: "/scratch/project_2010633/minigpt4_video/Llama-2-7b-chat-hf"
  ckpt: "/scratch/project_2010633/minigpt4_video/MiniGPT4-Video/checkpoints/video_captioning_llama_checkpoint_last.pth" # set the checkpoint to start the training from
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  length: 50
  use_grad_checkpoint_llm: True
  max_context_len: 3600
  architectures: [
    "MiniGPT4_Video"
  ]
  device: "cuda"
  drop_path_rate: 0 
  img_size: 224
  model_type: "minigpt4_video"
  num_query_token: 32
  prompt: ""
  torch_dtype: "float32"
  vit_precision: "fp16"
  vit_model: "eva_clip_g"
  lora_target_modules : ["q_proj","v_proj"]
  lora_dropout: 0.05
  remove_template: false
  prompt_path: ""
  token_pooling: True


datasets:
  video_chatgpt: #99378 row  - 13224 video
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 100
run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-7
  warmup_lr: 3e-5

  weight_decay: 0.0005
  max_epoch: 30
  num_workers: 4
  warmup_steps: 2000
  iters_per_epoch: 1000

  seed: 42
  output_dir: "/scratch/project_2010633/minigpt4_video/train_output"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]

  device: "cuda"
  world_size: 4
  dist_url: "env://"
  distributed: True
